### ISSUE TITLE
Что то поменялось на лосте. 

### ISSUE THREAD

**Issue by sovaby** [anteo/plugin.video.lostfilm.tv#15]
Из все сериалы ничего не запускает.
В библиотеку не добавляет из библиотеки тоже не запускает.
Запустить можно только новинки. первая страница.

`19:51:54 T:139997873170176 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.ValueError'>
  Error Contents: time data u'11.10.2016' does not match format u'%d.%m.%Y %H:%M'
  Traceback (most recent call last):
  File "/home/xbmc/.kodi/addons/plugin.video.lostfilm.tv/addon.py", line 12, in <module>
  run_plugin()
  File "/home/xbmc/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/support/common.py", line 348, in run_plugin
  plugin.run()
  File "/home/xbmc/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/xbmcswift2/plugin.py", line 342, in run
  items = self._dispatch(self.request.path)
  File "/home/xbmc/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/xbmcswift2/plugin.py", line 303, in _dispatch
  listitems = view_func(*_items)
  File "/home/xbmc/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/lostfilm/routes.py", line 58, in browse_series
  episodes = scraper.get_series_episodes(series_id)
  File "/home/xbmc/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/lostfilm/scraper.py", line 203, in get_series_episodes
  release_date = str_to_date(release_date, '%d.%m.%Y %H:%M') if release_date else None
  File "/home/xbmc/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/support/common.py", line 191, in str_to_date
  return datetime.date(_(time.strptime(date_string, date_format)[0:3]))
  File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
  return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
  (data_string, format))
  ValueError: time data u'11.10.2016' does not match format u'%d.%m.%Y %H:%M'
  -->End of Python script error report<--
  19:51:54 T:139997873170176 INFO: Python script stopped
  19:51:54 T:139997873170176 DEBUG: Thread LanguageInvoker 139997873170176 terminating
  19:51:54 T:140001005590848 DEBUG: ------ Window Init (DialogBusy.xml) ------
  19:51:54 T:139997864777472 DEBUG: WaitOnScriptResult - plugin exited prematurely - terminating
  19:51:54 T:140001005590848 ERROR: GetDirectory - Error getting plugin://plugin.video.lostfilm.tv/browse_series/231
  19:51:54 T:140001005590848 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.lostfilm.tv/browse_series/231) failed
  19:51:54 T:140001005590848 DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.lostfilm.tv/browse_all_series)
  19:51:54 T:140001005590848 DEBUG: ParentPath = [plugin://plugin.video.lostfilm.tv/]
  19:51:54 T:140001005590848 DEBUG: Loading items: 240, directory: plugin://plugin.video.lostfilm.tv/browse_all_series sort method: 0, ascending: false
  19:51:54 T:139997873170176 DEBUG: Thread BackgroundLoader start, auto delete: false
  19:51:54 T:139997873170176 DEBUG: Thread BackgroundLoader 139997873170176 terminating`

**Comment by prieditism** [comment]
The same and almost more than month. (FireTV Stick)

**Comment by alexvamp** [comment]
+1

**Comment by sovaby** [comment]
Change plugin.video.lostfilm.tv/resources/lib/lostfilm/scraper.py", line 203
to release_date = str_to_date(release_date, '%d.%m.%Y') if release_date else None

**Comment by prieditism** [comment]
This doesn't solves library update problem. With fix you can open saved libraries and shows, but library doesn't updates as before. Needs additional fix.

**Comment by zachross90210** [comment]
почините уже , надоел он уже пиликать круглые сутки

**Comment by alexvamp** [comment]
Ну не знаю.  У меня после совета sovaby  **ВСЕ** заработало! В том числе и обновление библиотеки.

**Comment by prieditism** [comment]
Sovaby suggestions fix only part of problems. Library still doesnt updates

**Comment by sovaby** [comment]
After the fix, delete the library rebuild. I have everything updated and added.

После фикса удалите библиотеку и перестройте заново. У меня и добавляет и обновляет в библиотеке.

**Comment by prieditism** [comment]
doesn't helps. Removed library from video sources (media settings> library>video), readed via lostfilm.tv settings and the same error. can't update library

**Comment by GhostR111der** [comment]
Все работает после фикса от @sovaby! Спасибо огромное!

**Comment by albanu** [comment]
Господа, подскажите пожалуйста поподробнее как этот фикс осуществить. Ну или подскажите, где про это написано. У меня Kodi  16.1 на android 6.0.1.

**Comment by prieditism** [comment]
There has been some changes again in Kodi or Lostfilm side as this fix doesn't works anymore.

**Comment by prieditism** [comment]
or in Lostfilm side

**Comment by alexvamp** [comment]
Да - на днях опять перестал работать :(

**Comment by zachross90210** [comment]
ага и вместе с лостом плагин giraffe.seasonvar тоже (((

**Comment by yegorka6** [comment]
New issue, caused by one link with underscore for Черный список: http://www.lostfilm.tv/browse.php?cat=_214
I will post the details in separate issue, hopefully someone will fix it))

**Comment by prieditism** [comment]
Nothing works now. Ok, awaiting. Thanks in advance,.
