### ISSUE TITLE
Failure on lostfilm pages containing underscore

### ISSUE THREAD

**Issue by yegorka6** [anteo/plugin.video.lostfilm.tv#18]
Only the page with new episodes is working, When clicking on <<All Series>> the plugin fails with the exception below. Looks like Lostfilm started to use underscore for some series urls, in that case the correct url is http://www.lostfilm.tv/browse.php?cat=_300 and it fails for http://www.lostfilm.tv/browse.php?cat=300

18:12:11 T:9768  NOTICE: [support.abstract.scraper] Bulk fetching series with IDs 265, 145, 41, 212, 140, 281, 300, 199, 137, 143, 117, 129, 85, 248, 149, 203, 230, 266, 46 taken: 0.967597 seconds
18:12:11 T:9768   ERROR: [root] Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 783, in __bootstrap
                                                self.__bootstrap_inner()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\thread.py", line 73, in _worker
                                                work_item.run()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\thread.py", line 61, in run
                                                result = self.fn(*self.args, **self.kwargs)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 232, in get_series_info
                                                doc = self._get_series_doc(series_id)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 186, in _get_series_doc
                                                return self.fetch(self.BASE_URL + "/browse.php", {'cat': series_id})
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 112, in fetch
                                                self.response = super(LostFilmScraper, self).fetch(url, params, data, **request_params)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\support\abstract\scraper.py", line 60, in fetch
                                                raise ScraperError(32001, "Can't fetch URL: %s (%%s)" % url, lang(30000), cause=e)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\support\common.py", line 284, in __init__
                                                CausedException.__init__(self, **kwargs)
                                            ScraperError: Can't fetch URL: http://www.lostfilm.tv/browse.php (LostFilm.TV)
                                            Caused by 1 exception
                                              Traceback (most recent call last):
                                                ... (10 frames repeated)
                                                File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\support\abstract\scraper.py", line 52, in fetch
                                                  response.raise_for_status()
                                                File "C:\Users\Igal\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 893, in raise_for_status
                                                  raise HTTPError(http_error_msg, response=self)
                                              HTTPError: 403 Client Error: Forbidden for url: http://www.lostfilm.tv/browse.php?cat=300
18:12:11 T:8052   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.lostfilm.tv/browse_all_series
18:12:11 T:8052   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.lostfilm.tv/browse_all_series) failed

**Comment by Tommixoft** [comment]
open scraper.py and replace function in line 185 with this:

```
	try:
		res =  self.fetch(self.BASE_URL + "/browse.php", {'cat': series_id})
	except ScraperError:
		res =  self.fetch(self.BASE_URL + "/browse.php", {'cat': '_' + str(series_id)})
        return res
```
or go to my profile and download plugin from there

**Comment by yegorka6** [comment]
Thanks, @Tommixoft it handled the issue but raised a new exception))

01:14:03 T:10668   ERROR: [plugin.video.lostfilm.tv] 'NoneType' object has no attribute 'find'
01:14:03 T:10668   ERROR: Traceback (most recent call last):
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\service.py", line 20, in safe_update_library
                                                return update_library()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\common.py", line 349, in update_library
                                                series_episodes.update(scraper.get_series_episodes_bulk(ids))
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 233, in get_series_episodes_bulk
                                                results[_id] = future.result()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\_base.py", line 413, in result
                                                return self.__get_result()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\_base.py", line 372, in __get_result
                                                raise self._exception.raise_wrapped()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\thread.py", line 61, in run
                                                result = self.fn(*self.args, **self.kwargs)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 197, in get_series_episodes
                                                body = doc.find('div', {'class': 'mid'})
                                            AttributeError: 'NoneType' object has no attribute 'find'
01:14:03 T:10668  NOTICE: [plugin.video.lostfilm.tv] Scheduling next library update at 2017-01-27 13:14:03.995000
01:14:08 T:9348  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
01:14:08 T:9348  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'o': None} started...
01:14:08 T:9348  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'o': None} taken: 0.352756 seconds
01:14:08 T:9348  NOTICE: [support.abstract.scraper] Parsing episodes list started...
01:14:08 T:9348  NOTICE: [support.abstract.scraper] Got 15 episode(s) successfully
01:14:08 T:9348  NOTICE: [support.abstract.scraper] Parsing episodes list taken: 0.058745 seconds
01:14:08 T:9348  NOTICE: [support.abstract.scraper] Bulk fetching series with IDs 277, 294, 279 started...
01:14:08 T:10272  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'cat': 277} started...
01:14:08 T:1748  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'cat': 294} started...
01:14:08 T:3028  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'cat': 279} started...
01:14:09 T:10272  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'cat': 277} taken: 0.229686 seconds
01:14:09 T:10272  NOTICE: [support.abstract.scraper] Parsing series info with ID 277 started...
01:14:09 T:10272  NOTICE: [support.abstract.scraper] Parsing series info with ID 277 taken: 0.000013 seconds
01:14:09 T:1748  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'cat': 294} taken: 0.309770 seconds
01:14:09 T:1748  NOTICE: [support.abstract.scraper] Parsing series info with ID 294 started...
01:14:09 T:1748  NOTICE: [support.abstract.scraper] Parsing series info with ID 294 taken: 0.000019 seconds
01:14:09 T:3028  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'cat': 279} taken: 0.315791 seconds
01:14:09 T:3028  NOTICE: [support.abstract.scraper] Parsing series info with ID 279 started...
01:14:09 T:3028  NOTICE: [support.abstract.scraper] Parsing series info with ID 279 taken: 0.000013 seconds
01:14:09 T:9348  NOTICE: [support.abstract.scraper] Bulk fetching series with IDs 277, 294, 279 taken: 0.323013 seconds
01:14:09 T:9348   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find'
                                            Traceback (most recent call last):
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\addon.py", line 12, in <module>
                                                run_plugin()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\support\common.py", line 348, in run_plugin
                                                plugin.run()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\xbmcswift2\plugin.py", line 342, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\xbmcswift2\plugin.py", line 303, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\routes.py", line 143, in index
                                                items = itemify_episodes(batch_res)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\common.py", line 86, in itemify_episodes
                                                series = scraper.get_series_bulk(series_ids)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 171, in get_series_bulk
                                                result = future.result()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\_base.py", line 413, in result
                                                return self.__get_result()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\_base.py", line 372, in __get_result
                                                raise self._exception.raise_wrapped()
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\concurrent\futures\thread.py", line 61, in run
                                                result = self.fn(*self.args, **self.kwargs)
                                              File "C:\Users\Igal\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 239, in get_series_info
                                                body = doc.find('div', {'class': 'mid'})
                                            AttributeError: 'NoneType' object has no attribute 'find'
                                            -->End of Python script error report<--
01:14:09 T:11536   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.lostfilm.tv/
01:14:09 T:11536   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.lostfilm.tv/) failed

**Comment by Tommixoft** [comment]
Then im idiot. i fixed it 2 times and looks like it still generates error :) Problem is that this plugin is written by noob. The bigger problem is that i do not know python and KODI API, so it's hard to fix. But programmers who do not make sure they have data to work with is noobs. And this guy don't check variables that's why now plugin don't work.

Also i see that LostFilm created totally new look, and they will switch to new look soon. So this plugin doomed to stop working. Sad cause it's really good

**Comment by Ksantor** [comment]
@Tommixoft it is not yet doomed (at least there still is a vague chance for an update). See the #19
