### ISSUE TITLE
В чем может быть проблема?

### ISSUE THREAD

**Issue by maltsevvv** [anteo/plugin.video.lostfilm.tv#21]
15:02:33.594 T:4944  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
15:02:33.703 T:4944  NOTICE: [support.abstract.scraper] Authorization started...
15:02:33.704 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params None started...
15:02:34.146 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params None taken: 0.440854 seconds
15:02:34.147 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://login1.bogi.ru/login.php with params {u'referer': u'http://www.lostfilm.tv/'} started...
15:02:34.334 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://login1.bogi.ru/login.php with params {u'referer': u'http://www.lostfilm.tv/'} taken: 0.186824 seconds
15:02:34.360 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://old.lostfilm.tv/blg.php?ref=aHR0cDovL3d3dy5sb3N0ZmlsbS50di8= with params None started...
15:02:34.865 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://old.lostfilm.tv/blg.php?ref=aHR0cDovL3d3dy5sb3N0ZmlsbS50di8= with params None taken: 0.503056 seconds
15:02:34.880 T:4944  NOTICE: [support.abstract.scraper] Authorization taken: 1.176251 seconds
15:02:34.882 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'o': None} started...
15:02:34.972 T:4944  NOTICE: [support.abstract.scraper] Fetching URL http://www.lostfilm.tv/browse.php with params {u'o': None} taken: 0.088701 seconds
15:02:34.976 T:4944  NOTICE: [support.abstract.scraper] Parsing episodes list started...
15:02:34.987 T:4944  NOTICE: [support.abstract.scraper] Parsing episodes list taken: 0.009712 seconds
15:02:35.017 T:4944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: need more than 0 values to unpack
                                            Traceback (most recent call last):
                                              File "C:\Users\Malts\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\addon.py", line 12, in <module>
                                                run_plugin()
                                              File "C:\Users\Malts\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\support\common.py", line 348, in run_plugin
                                                plugin.run()
                                              File "C:\Users\Malts\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\xbmcswift2\plugin.py", line 342, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Malts\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\xbmcswift2\plugin.py", line 303, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\Malts\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\routes.py", line 116, in index
                                                episodes = scraper.browse_episodes(skip)
                                              File "C:\Users\Malts\AppData\Roaming\Kodi\addons\plugin.video.lostfilm.tv\resources\lib\lostfilm\scraper.py", line 278, in browse_episodes
                                                episode_titles, original_titles = zip(*[parse_title(t) for t in titles])
                                            ValueError: need more than 0 values to unpack
                                            -->End of Python script error report<--
15:02:35.317 T:7532   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.lostfilm.tv/
15:02:35.322 T:7532   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.lostfilm.tv/) failed

**Comment by Jabberwacky** [comment]
Наверное, это потому, что почти год назад Лостфилм полностью переделал весь сайт.
